### ISSUE TITLE
大陆服使用就爆炸

### ISSUE THREAD

**Issue by yunzlp** [flier268/POE-Stash-Sorter-v2#1]
扫到第二件装备就duang
************** 异常文本 **************
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 Poe整理倉庫v2.Form1.<GetWarehouse>d__50.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

**Comment by flier268** [comment]
大陸服我沒考慮過，所以沒有特別去設計
