### ISSUE TITLE
Please update

### ISSUE THREAD

**Issue by Ron0x99** [flier268/POE-Stash-Sorter-v2#14]
Hi there, I was using your software all the time until the Blight update. POE got some new gems and it seems that breaks your software. Could you update it again?

**Comment by flier268** [comment]
I had update it

**Comment by yamio** [comment]
感謝作者的辛勞，但是我試著下載VS編譯，也許是因為不熟悉。
我仍會遇到一些錯誤導致無法運行，能否拜託一下作者編譯出來提供下載呢？

**Comment by flier268** [comment]
https://github.com/flier268/POE-Stash-Sorter-v2/releases
