### ISSUE TITLE
Would love an update.

### ISSUE THREAD

**Issue by TimeFlex1** [flier268/POE-Stash-Sorter-v2#15]
Ive tried fixing it myself but I couldnt get anything working. =/
I tried to get it to pull from US servers on PoEDB. Could you add a feature to choose which server to pull from. Thanks!
Even after all these years I still use your sorter. =)

**Comment by flier268** [comment]
did u have other choose(other than poedb)?

**Comment by flier268** [comment]
https://github.com/flier268/POE-Stash-Sorter-v2/releases
