### ISSUE TITLE
English please?

### ISSUE THREAD

**Issue by Chaaaaaaaaarlie** [flier268/POE-Stash-Sorter-v2#2]
Hey mate, could you possibly make a english translation of it?
Sadly can't speak mandarin ^^

**Comment by flier268** [comment]
it is traditional Chinese
i am editting,I will success it,maybe
But I am not good at English,so I need someone report it.

**Comment by Chaaaaaaaaarlie** [comment]
Will contribute as much as I can.

**Comment by flier268** [comment]
@Chaaaaaaaaarlie I have add English Language in 2.0.0.7,try it

**Comment by Chaaaaaaaaarlie** [comment]
could you compile it please? :)

**Comment by flier268** [comment]
See"Release",newst one is

**Comment by Chaaaaaaaaarlie** [comment]
Whoops, my bad :)

![grafik](https://user-images.githubusercontent.com/10680114/33266318-68cb1f5c-d375-11e7-916e-6772483f32f6.png)

Looks awesome so far, only thing off I found so far, it still can't order unique maps?
(are "bigger" items planned for the future? like 2width, 3higth)

**Comment by flier268** [comment]
this form is because that,something is not write in my database,so,maybe you need to add it yourself

I forgot to edit this,it is my fail,I will update it this weekend

**Comment by Chaaaaaaaaarlie** [comment]
Well apparently if I try to save something it gives me this:

`See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IO.FileNotFoundException: Could not find file 'E:\Bots\PoE Stash Sorter\POE整理倉庫v2\ItemList_Adden.txt'.
File name: 'E:\Bots\PoE Stash Sorter\POE整理倉庫v2\ItemList_Adden.txt'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding)
   at Poe整理倉庫v2.Form2.button1_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Poe整理倉庫v2
    Assembly Version: 2.0.0.7
    Win32 Version: 2.0.0.7
    CodeBase: file:///E:/Bots/PoE%20Stash%20Sorter/POE%E6%95%B4%E7%90%86%E5%80%89%E5%BA%ABv2/Poe%E6%95%B4%E7%90%86%E5%80%89%E5%BA%ABv2.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Flier.SuperTools
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.1
    CodeBase: file:///E:/Bots/PoE%20Stash%20Sorter/POE%E6%95%B4%E7%90%86%E5%80%89%E5%BA%ABv2/Flier.SuperTools.DLL
----------------------------------------
Newtonsoft.Json
    Assembly Version: 10.0.0.0
    Win32 Version: 10.0.3.21018
    CodeBase: file:///E:/Bots/PoE%20Stash%20Sorter/POE%E6%95%B4%E7%90%86%E5%80%89%E5%BA%ABv2/Newtonsoft.Json.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
mscorlib.resources
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_de_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
Poe整理倉庫v2.resources
    Assembly Version: 2.0.0.7
    Win32 Version: 2.0.0.7
    CodeBase: file:///E:/Bots/PoE%20Stash%20Sorter/POE%E6%95%B4%E7%90%86%E5%80%89%E5%BA%ABv2/en/Poe%E6%95%B4%E7%90%86%E5%80%89%E5%BA%ABv2.resources.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.


`

**Comment by flier268** [comment]
I forgot to add a code to automatically create the text file,you need to create one yourself
just create a text file named "ItemList_Adden.txt" under .exe file path,i am sorry about it

**Comment by Chaaaaaaaaarlie** [comment]
Works awesome now, thanks a bunch :)

**Comment by flier268** [comment]
Fixed.If you have any problem,report it please
