### ISSUE TITLE
Did't find Path Of Exile error

### ISSUE THREAD

**Issue by TimeFlex1** [flier268/POE-Stash-Sorter-v2#3]
Does this work with the steam version of the game. I cannot get it to work at all. Steam filename is PathOfExile_x64Steam.exe

**Comment by flier268** [comment]
OK,I will update it this Saturday,too

**Comment by flier268** [comment]
Updated. Does it fix?

**Comment by TimeFlex1** [comment]
Works perfectly. Thank you!
Side note, could you make the reload button key bind to F8.
Awesome software keep it up.

**Comment by flier268** [comment]
This is a good idea.
