### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by TimeFlex1** [flier268/POE-Stash-Sorter-v2#4]
1. Option to save pages and have the scan window be able to move objects and save them and certain orders.
2. Profiles for certain pages. Example, If a page scan reads that there is mostly currency on a page it will automatically have a profile for that page to sort in a certain order.
3. Have settings saved in a file so everything will be the same every time you open the program.

I'll think of more. So far everything is awesome. Keep it up!

**Comment by flier268** [comment]
1.It need time.But I don't have a lot of time.
2.The same as 1
3.When you update to new version ,you don't need to replace Poe整理倉庫v2.cfg,this file save your config.
