### ISSUE TITLE
自動新增資料庫?

### ISSUE THREAD

**Issue by yamio** [flier268/POE-Stash-Sorter-v2#5]
之前偶爾會遇到這種，我猜大概原因這物件可能是資料庫名稱以外的。
不過這功能是有實裝嗎？
我好像幾乎每次都會跳開　無法新增下去

**Comment by flier268** [comment]
資料庫是從其他地方載下來的，但有些物品可能會不在資料庫內，因此可能需要手動新增，手動新增這個功能我是有做出來的，正常應該是不會有這個問題
請問你的版本是多少，還有，遊戲的介面是繁體中文或英文的嗎？，如果版本是最新的，遊戲又是繁體中文或英文，請將錯誤資訊截圖給我或貼文字給我，我再看看是哪邊的問題，謝謝
