### ISSUE TITLE
sort by Skill Gem lvl  and keybind F10

### ISSUE THREAD

**Issue by Felinmorph** [flier268/POE-Stash-Sorter-v2#6]
hi, 
first off, wounderfull app!

Could you please add the ability to sort by skill gem level
and enable F10 as a Hotkey?

Would realy appreciate it  :-)

**Comment by flier268** [comment]
Sort by gem level is easy.But I don't understand about Hotkey,the start Hotkey is customized

**Comment by Felinmorph** [comment]
I can only select none, F1, F2, F3, F4, F5, F6, F7, F8, F9, F11, F12, F13, F14 and F15 but not F10 in the dropdown lists - independent of selected language using version 2.0.0.9

**Comment by flier268** [comment]
Check update,I have update it.
