### ISSUE TITLE
您好 

### ISSUE THREAD

**Issue by asd3427** [flier268/POE-Stash-Sorter-v2#7]
想請問一下是否可以支援公會倉庫取出物品呢??? 還有你會更新POEHUD嗎??? 台服都不能用

**Comment by flier268** [comment]
公會倉庫取出物品是什麼意思？
POEHUD不是我寫的，我也不會更新，因為我還不會抓記憶體，然後台服是可以使用的，直接用國際版的可以使用部分功能，但要記得把Item Alert關掉

**Comment by asd3427** [comment]
就是把工會裡面的東西取出 來放到身上 例如 我在工會裡面放了很ˋ多傳說戒子一個一個取太麻煩 用你的程式就可以自動取出到身上 這樣解釋有清楚嗎???

**Comment by flier268** [comment]
全部都拿出來嗎？意義不明，是有多少東西要拿出來

**Comment by asd3427** [comment]
對全部拿出來 東西很多 好幾個賽季類積下來的 太多了 一˙各一個拿很累><::

**Comment by flier268** [comment]
我應該是會弄一個快捷鍵，按一下就拿取滑鼠所指向的物品

**Comment by asd3427** [comment]
應該可以XDD

**Comment by asd3427** [comment]
話說大大 那個 poehud 為甚麼 他的怪物顯示monster  Alert 不能用了了阿  以前不是會顯示哪裡有怪嗎= =
??

**Comment by flier268** [comment]
我還是覺得這功能跟整理倉庫沒什麼關係，不太想放到程式裡面，而且這樣又要多hook一個按鍵，什麼都加進來會變太臃腫

不知道，台版跟國際版的記憶體位置本來就不太一樣，不能用很正常

**Comment by asd3427** [comment]
好的 話說你的程式是用c寫的對嗎？

**Comment by flier268** [comment]
C# 跟C長得有點像
