### ISSUE TITLE
Unable to run after updating with DataGetter.exe

### ISSUE THREAD

**Issue by Mushie84** [flier268/POE-Stash-Sorter-v2#9]
After running DataGetter.exe, when running the application the following error message is given.

![image](https://user-images.githubusercontent.com/46676349/51112965-3ce91480-184c-11e9-913b-4e9c841176b5.png)

I've also attached the updated ItemList.txt.
[ItemList.txt](https://github.com/flier268/POE-Stash-Sorter-v2/files/2755126/ItemList.txt)

Steps to reproduce
1 - Download latest Release
2 - Run DataGetter.exe
3 - Have successful update
4 - Run Poe整理倉庫v2.exe

**Comment by flier268** [comment]
It is because that Itemlist.txt is following poedb.tw

But,after POE update,the web will update something.

So,DataGetter.exe also need update too.I will try to update it tomorrow.

**Comment by flier268** [comment]
Try 2.0.1.3
